add:[ .bash_profile, .bashrc, .zshenv, bin/tes ] improve:[ .tmux.conf, .zshrc, dotmanager ]

diff --git a/bin/dotmanager b/bin/dotmanager
--- a/bin/dotmanager
+++ b/bin/dotmanager
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-dotfiles=$(ls -A $HOME/dotfiles | grep -v 'setup\|bi\|.git\|README.md\|.DS_Store')
+dotfiles=$(ls -A $HOME/dotfiles | grep -v 'setup\|bin\|.git\|README.md\|.DS_Store')
 
 function dotmanager::help() {
   echo "usage: dotmanager [COMMANDS] [OPTIONS]"
@@ -37,9 +37,9 @@ function dotmanager::deploy::dotfiles() {
   local i=0
   for dotfile in ${dotfiles[@]}; do
     if [ ! -e $HOME/$dotfile ]; then
-      ((i++))
+      (( i++ ))
       ln -s $HOME/dotfiles/$dotfile $HOME/$dotfile
-      [[ $? = 0 ]] && echo "linked : $dotfile" || echo "link failed : $dotfile"
+      [[ $? = 0 ]] && echo "+ linked : $dotfile" || echo "! link failed : $dotfile"
     fi
   done
   [ $i = 0 ] && echo "All dotfiles are already linked."
@@ -47,16 +47,17 @@ function dotmanager::deploy::dotfiles() {
 
 function dotmanager::deploy::commands() {
   local j=0
-  [[ ! $PATH =~ "$HOME/dotfiles/bin" ]] && echo "export PATH=\$PATH:\$HOME/dotfiles/bin" >> $HOME/.zshenv
   commands=$(ls $HOME/dotfiles/bin)
   for command in ${commands[@]}; do
-    if [ ! -x $HOME/dotfiles/bin/$command ] ; then
-      ((j++))
-      chmod a+x ~/dotfiles/bin/$commad
-      [[ $? = 0 ]] && echo "excutable: $command" || echo "failed to make it excutable: $command"
+    if [ ! -x $HOME/dotfiles/bin/$command ]; then
+      (( j++ ))
+      chmod a+x ~/dotfiles/bin/$command
+      [[ $? = 0 ]] && echo "+ grant execute permission: $command" || echo "! failed to make it excutable: $command"
     fi
   done
-  [ $j = 0 ] && echo "All commands are already excutable."
+  if [ $j = 0 ]; then
+    echo "All commands are already excutable."
+  fi
 }
 
 function dotmanager::clean() {
@@ -66,7 +67,7 @@ function dotmanager::clean() {
     echo
     for dotfile in ${dotfiles[@]}; do
       unlink ~/$dotfile
-      [[ $? = 0 ]] && echo "unlinked : $dotfile" || echo "unlink failed : $dotfile"
+      [[ $? = 0 ]] && echo "- unlinked : $dotfile" || echo "! unlink failed : $dotfile"
     done
     rm -rf ~/dotfiles
     echo "dotmanager::"
