improve:[ .vimrc, .zshenv, .zshrc, imgcat ]

diff --git a/bin/imgcat b/bin/imgcat
--- a/bin/imgcat
+++ b/bin/imgcat
@@ -2,31 +2,51 @@
 
 # tmux requires unrecognized OSC sequences to be wrapped with DCS tmux;
 # <sequence> ST, and for all ESCs in <sequence> to be replaced with ESC ESC. It
-# only accepts ESC backslash for ST.
+# only accepts ESC backslash for ST. We use TERM instead of TMUX because TERM
+# gets passed through ssh.
 function print_osc() {
-    if [[ -n $TERM ]] ; then
+    if [[ $TERM == screen* ]] ; then
         printf "\033Ptmux;\033\033]"
     else
         printf "\033]"
     fi
 }
 
-function print_csi() {
-    printf "\033["
-}
-
 # More of the tmux workaround described above.
 function print_st() {
-    if [[ -n $TERM ]] ; then
+    if [[ $TERM == screen* ]] ; then
         printf "\a\033\\"
     else
         printf "\a"
     fi
 }
 
-# Return the height of the image, or 200 if imagemagick is unavailable.
-function get_height() {
-    identify -format "%h" - 2>/dev/null || echo 200
+function load_version() {
+    if [ -z ${IMGCAT_BASE64_VERSION+x} ]; then
+        export IMGCAT_BASE64_VERSION=$(base64 --version 2>&1)
+    fi
+}
+
+function b64_encode() {
+    load_version
+    if [[ "$IMGCAT_BASE64_VERSION" =~ GNU ]]; then
+        # Disable line wrap
+        base64 -w0
+    else
+        base64
+    fi
+}
+
+function b64_decode() {
+    load_version
+    if [[ "$IMGCAT_BASE64_VERSION" =~ fourmilab ]]; then
+      BASE64ARG=-d
+    elif [[ "$IMGCAT_BASE64_VERSION" =~ GNU ]]; then
+      BASE64ARG=-di
+    else
+      BASE64ARG=-D
+    fi
+    base64 $BASE64ARG
 }
 
 # print_image filename inline base64contents print_filename
@@ -36,35 +56,14 @@ function get_height() {
 #   print_filename: If non-empty, print the filename 
 #                   before outputting the image
 function print_image() {
-    VERSION=$(base64 --version 2>&1)
-    if [[ "$VERSION" =~ fourmilab ]]; then
-      BASE64ARG=-d
-    elif [[ "$VERSION" =~ GNU ]]; then
-      BASE64ARG=-di
-    else
-      BASE64ARG=-D
-    fi
-
-    local -i HEIGHT=$(printf "%s" "$3" | base64 $BASE64ARG | get_height)
-    HEIGHT=$(( (HEIGHT + 19) / 20 ))
-
-    for (( I = 0; I < $HEIGHT; I++ )); do
-      printf "\n"
-    done
-    print_csi
-    printf "?25l"
-    print_csi
-    printf "${HEIGHT}F"
-
     print_osc
     printf '1337;File='
     if [[ -n "$1" ]]; then
-      printf 'name='`printf "%s" "$1" | base64`";"
+      printf 'name='`printf "%s" "$1" | b64_encode`";"
     fi
 
-    printf "%s" "$3" | base64 $BASE64ARG | wc -c | awk '{printf "size=%d",$1}'
+    printf "%s" "$3" | b64_decode | wc -c | awk '{printf "size=%d",$1}'
     printf ";inline=$2"
-    printf ";height=$HEIGHT"
     printf ":"
     printf "%s" "$3"
     print_st
@@ -72,11 +71,6 @@ function print_image() {
     if [[ -n "$4" ]]; then
       echo $1
     fi
-
-    print_csi
-    printf "${HEIGHT}E"
-    print_csi
-    printf "?25h"
 }
 
 function error() {
@@ -86,6 +80,13 @@ function error() {
 function show_help() {
     echo "Usage: imgcat [-p] filename ..." 1>& 2
     echo "   or: cat filename | imgcat" 1>& 2
+}
+
+function check_dependency() {
+  if ! (builtin command -V "$1" > /dev/null 2>& 1); then
+    echo "imgcat: missing dependency: can't find $1" 1>& 2
+    exit 1
+  fi
 }
 
 ## Main
@@ -102,6 +103,10 @@ if [ $has_stdin = f -a $# -eq 0 ]; then
     exit
 fi
 
+check_dependency awk
+check_dependency base64
+check_dependency wc
+
 # Look for command line flags.
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -112,15 +117,25 @@ while [ $# -gt 0 ]; do
     -p|--p|--print)
         print_filename=1
         ;;
+    -u|--u|--url)
+        check_dependency curl
+        encoded_image=$(curl -s "$2" | b64_encode) || (error "No such file or url $2"; exit 2)
+        has_stdin=f
+        print_image "$2" 1 "$encoded_image" "$print_filename"
+        set -- ${@:1:1} "-u" ${@:3}
+        if [ "$#" -eq 2 ]; then
+            exit
+        fi
+        ;;
     -*)
         error "Unknown option flag: $1"
         show_help
         exit 1
-        ;;
+      ;;
     *)
         if [ -r "$1" ] ; then
             has_stdin=f
-            print_image "$1" 1 "$(base64 < "$1")" "$print_filename"
+            print_image "$1" 1 "$(b64_encode < "$1")" "$print_filename"
         else
             error "imgcat: $1: No such file or directory"
             exit 2
@@ -132,7 +147,7 @@ done
 
 # Read and print stdin
 if [ $has_stdin = t ]; then
-    print_image "" 1 "$(cat | base64)" ""
+    print_image "" 1 "$(cat | b64_encode)" ""
 fi
 
 exit 0
