remove:[ ../bin/git-commit-automatically, ../bin/git-log-fzf, command_manager ] rename:[ ../bin/display-colors -> display-colors, ../bin/dot -> dot, ../bin/google -> google, ../bin/tmux-status-line -> tmux-status-line ] improve:[ .zshrc ]

diff --git a/commands/dot b/commands/dot
--- a/commands/dot
+++ b/commands/dot
@@ -1,6 +1,5 @@
 #!/bin/sh
 
-
 dotfiles=( ".vimrc" ".zshrc" ".tmux.conf" "setup/Brewfile" )
 
 function dot_help() {
@@ -35,11 +34,14 @@ function dot() {
       ;;
 
       "deploy" )
-        for file in ${dotfiles[@]}; do
-          ln -s -f ~/dotfiles/$file ~
-        done
-        for file in $(ls ~/dotfiles/bin); do
-          chmod a+x ~/dotfiles/bin/$file
+        for file in $(ls ~/dotfiles/commands); do
+          chmod a+x ~/dotfiles/commands/$file
+          ln -s ~/dotfiles/commands/$file /usr/local/bin/$file
+          if [[ $? = 0 ]] ; then
+            echo "deploy succeed : $file" 
+          else
+            echo "error! : $file"
+          fi  
         done
       ;;
 
