improve:[ dotmanager, install.sh ]

diff --git a/commands/dotmanager b/commands/dotmanager
--- a/commands/dotmanager
+++ b/commands/dotmanager
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 dotfiles=$(ls -A $HOME/dotfiles | grep -v 'setup\|commands\|.git\|README.md\|.DS_Store')
+commands=$(ls $HOME/dotfiles/commands)
 
 function dotmanager_help() {
   echo "usage: dotmanager [COMMANDS] [OPTIONS]"
@@ -38,29 +39,21 @@ function dotmanager() {
         cd $HOME
         local i=0
         local j=0
-        for dotfile in $dotfiles; do
+        for dotfile in ${dotfiles[@]}; do
           if [ ! -e $dotfile ]; then
-            $((i++))
+            ((i++))
             ln -s $HOME/dotfiles/$dotfile $HOME/$dotfile
-            if [[ $? = 0 ]] ; then
-              echo "link success : $dotfile" 
-            else
-              echo "link failed : $dotfile"
-            fi  
+            [[ $? = 0 ]] && echo "linked: $dotfile" || echo "link failed : $dotfile"
           fi
         done
         [ $i = 0 ] && echo "All dotfiles are already linked."
         cd /usr/local/bin
-        for command in $(ls ~/dotfiles/commands); do
+        for command in ${commands[@]}; do
           if [ ! -e $command ] ; then
-            $((j++))
+            ((j++))
            chmod a+x ~/dotfiles/commands/$commad
             ln -s ~/dotfiles/commands/$command /usr/local/bin/$command
-            if [[ $? = 0 ]] ; then
-              echo "link success : $command" 
-            else
-              echo "link faild : $command"
-            fi  
+            [[ $? = 0 ]] && echo "linked : $command" || echo "link failed : $command"
           fi
         done
         [ $j = 0 ] && echo "All commands are already linked."
@@ -71,11 +64,13 @@ function dotmanager() {
         echo "dotmanager: remove dotfiles? [n/y]: "
         read answer
         if [[ "$answer" = "y" ]] ; then
-          for file in ${dotfiles[@]}; do
-            unlink ~/$file
+          for dotfile in ${dotfiles[@]}; do
+            unlink ~/$dotfile
+            [[ $? = 0 ]] && echo "unlinked : $dotfile" || echo "unlink failed : $dotfile"
           done
-          for file in $(ls ~/dotfiles/commands); do
-            unlink /usr/local/bin/$file
+          for command in ${commands[@]}; do
+            unlink /usr/local/bin/$command
+            [[ $? = 0 ]] && echo "unlinked : $command" || echo "unlink failed : $command"
           done
           rm -rf ~/dotfiles
           echo    "dotmanager: dotfiles were removed."
@@ -85,20 +80,27 @@ function dotmanager() {
       ;;
 
       "init" )
-        if ! type brew >/dev/null 2>&1 ; then
-          if [ $(uname -s) = "Darwin" ]; then
-            cp ~/dotfiles/setup/Brewfile ~
+        if [ $(uname -s) = "Darwin" ]; then
+          if ! type brew >/dev/null 2>&1
             echo "dotmanager: installing Homebrew ..."
             /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-            brew tap Homebrew/bundle
-            brew bundle
-            rm ~/Brewfile
-          elif [ $(uname -s) = "Linux" ]; then
-            sudo apt-get install curl git ruby zsh
-          else
-            echo "dotmanager: not support your OS"
           fi
+          cp ~/dotfiles/setup/Brewfile ~
+          brew tap Homebrew/bundle
+          brew bundle
+          rm $HOME/Brewfile
+        elif [ $(uname -s) = "Linux" ]; then
+          if type apt-get >/dev/null 2>&1
+            echo "Installing curl, git, ruby, zsh with 'apt-get' Please put your Password."
+            sudo apt-get install curl git ruby zsh
+          elif type yum >/dev/null 2>&1
+            echo "Installing curl, git, ruby, zsh with 'yum' Please put your Password."
+            ##############
+          fi
+        else
+          echo "dotmanager: not support your OS"
         fi
+
         if [ ! $SHELL == "/bin/zsh" ] ; then
           echo "dotmanager: change shell to zsh, please put your password"
           chsh -s /bin/zsh
